(function(){
  'use strict';
  const JSI=window.JSI;
  const $=id=>document.getElementById(id);
  const els={
    canvas:$('artCanvas'),artboard:$('artboard'),status:$('statusText'),title:$('artTitle'),meta:$('artMeta'),
    style:$('styleSelect'),palette:$('paletteSelect'),seed:$('seedInput'),complexity:$('complexityRange'),density:$('densityRange'),motion:$('motionRange'),balance:$('balanceRange'),stroke:$('strokeRange'),detail:$('detailRange'),mirror:$('mirrorToggle'),ratio:$('ratioSelect'),quality:$('qualitySelect'),
    complexityV:$('complexityValue'),densityV:$('densityValue'),motionV:$('motionValue'),balanceV:$('balanceValue'),strokeV:$('strokeValue'),detailV:$('detailValue')
  };
  let settings=Object.assign({},JSI.presets.DEFAULTS);let artwork=null;let regenTimer=0;let busy=false;
  const coarsePointer=window.matchMedia&&window.matchMedia('(pointer: coarse)').matches;
  const styleLabels={'flow-garden':'Flow Garden','paper-cut':'Paper Cut','topographic':'Topographic','geo-collage':'Geo Collage','botanical':'Botanical','orbit-field':'Orbit Field'};
  function populatePalettes(){for(const [key,p] of Object.entries(JSI.presets.PALETTES)){const o=document.createElement('option');o.value=key;o.textContent=p.label;els.palette.appendChild(o)}}
  function read(){return{style:els.style.value,palette:els.palette.value,complexity:+els.complexity.value,density:+els.density.value,motion:+els.motion.value,balance:+els.balance.value,stroke:+els.stroke.value,detail:+els.detail.value,mirror:els.mirror.checked,ratio:els.ratio.value,quality:els.quality.value}}
  function syncOutputs(){els.complexityV.textContent=els.complexity.value;els.densityV.textContent=els.density.value;els.motionV.textContent=els.motion.value;els.balanceV.textContent=els.balance.value;els.strokeV.textContent=Math.round(+els.stroke.value)+'%';els.detailV.textContent=els.detail.value}
  function applySettingsToControls(s){els.style.value=s.style;els.palette.value=s.palette;els.complexity.value=s.complexity;els.density.value=s.density;els.motion.value=s.motion;els.balance.value=s.balance;els.stroke.value=s.stroke;els.detail.value=s.detail;els.mirror.checked=s.mirror;els.ratio.value=s.ratio;els.quality.value=s.quality;syncOutputs();setRatio()}
  function setRatio(){const parts=els.ratio.value.split(':').map(Number);const n=parts[0]/parts[1];els.artboard.style.aspectRatio=els.ratio.value.replace(':',' / ');els.artboard.style.setProperty('--art-ratio-number',String(n))}
  function setStatus(t){els.status.textContent=t}
  function updateCaption(){if(!artwork)return;els.title.textContent=artwork.title;els.meta.textContent=`${styleLabels[artwork.settings.style]} · ${artwork.primitives.length} forms · ${artwork.seed}`}
  function render(){if(!artwork)return;JSI.renderer.render(els.canvas,artwork);updateCaption()}
  function generate(opts={}){if(busy)return;busy=true;clearTimeout(regenTimer);settings=read();const seed=JSI.random.normalize(opts.newSeed?JSI.random.makeSeed():els.seed.value);els.seed.value=seed;setRatio();setStatus('Generating…');
    requestAnimationFrame(()=>{try{artwork=JSI.engine.generate(seed,settings);render();setStatus('Ready')}catch(e){console.error(e);setStatus('Generation failed')}finally{busy=false}})}
  function scheduleGenerate(delay=130){clearTimeout(regenTimer);setStatus('Updating…');regenTimer=setTimeout(()=>generate(),delay)}
  function rerenderOnly(){settings=read();if(!artwork)return generate();artwork.settings=Object.assign({},artwork.settings,settings);artwork.background=JSI.presets.PALETTES[settings.palette].bg;setRatio();render();setStatus('Ready')}
  function surprise(){const styles=Array.from(els.style.options).map(o=>o.value),pals=Object.keys(JSI.presets.PALETTES),r=JSI.random.create(JSI.random.makeSeed());els.style.value=r.pick(styles);els.palette.value=r.pick(pals);els.complexity.value=r.int(28,82);els.density.value=r.int(25,84);els.motion.value=r.int(18,88);els.balance.value=r.int(18,82);els.detail.value=r.int(28,82);els.stroke.value=r.int(75,135);els.mirror.checked=r.bool(.2);els.seed.value=JSI.random.makeSeed();syncOutputs();generate()}
  function reset(){settings=Object.assign({},JSI.presets.DEFAULTS,{seed:els.seed.value||JSI.random.makeSeed()});applySettingsToControls(settings);generate()}
  function save(){if(!artwork)return;const key='jsi-v3-collection';let arr=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]')}catch(_){arr=[]}const item={seed:artwork.seed,title:artwork.title,settings:artwork.settings,time:Date.now()};arr=[item,...arr.filter(x=>!(x.seed===item.seed&&x.settings.style===item.settings.style))].slice(0,24);localStorage.setItem(key,JSON.stringify(arr));$('saveBtn').textContent='♥ Saved';setTimeout(()=>$('saveBtn').textContent='♡ Save',1000)}
  function loadCollection(){const box=$('collectionList');box.textContent='';let arr=[];try{arr=JSON.parse(localStorage.getItem('jsi-v3-collection')||'[]')}catch(_){arr=[]}if(!arr.length){const e=document.createElement('div');e.className='empty-state';e.textContent='No saved artworks yet.';box.appendChild(e);return}for(const item of arr){const row=document.createElement('div');row.className='collection-item';const thumb=document.createElement('div');thumb.className='collection-thumb';const pal=JSI.presets.PALETTES[item.settings.palette]||JSI.presets.PALETTES.editorial;thumb.style.background=`linear-gradient(135deg,${pal.colors[0]},${pal.colors[2]},${pal.bg})`;const info=document.createElement('div');const strong=document.createElement('strong');strong.textContent=item.title;const small=document.createElement('small');small.textContent=`${styleLabels[item.settings.style]||item.settings.style} · ${item.seed}`;info.append(strong,small);const actions=document.createElement('div');actions.className='collection-actions';const open=document.createElement('button');open.className='small-btn';open.textContent='Open';open.onclick=()=>{applySettingsToControls(item.settings);els.seed.value=item.seed;$('collectionModal').close();generate()};const del=document.createElement('button');del.className='small-btn';del.textContent='×';del.setAttribute('aria-label','Delete');del.onclick=()=>{const next=arr.filter(x=>x!==item);localStorage.setItem('jsi-v3-collection',JSON.stringify(next));loadCollection()};actions.append(open,del);row.append(thumb,info,actions);box.appendChild(row)}}
  function openControls(){document.getElementById('controlPanel').classList.add('open');document.body.classList.add('controls-open');$('backdrop').hidden=false;$('mobileControlsBtn').setAttribute('aria-expanded','true')}
  function closeControls(){document.getElementById('controlPanel').classList.remove('open');document.body.classList.remove('controls-open');$('backdrop').hidden=true;$('mobileControlsBtn').setAttribute('aria-expanded','false')}
  function toggleFullscreen(){if(!document.fullscreenElement){document.documentElement.requestFullscreen?.();document.body.classList.add('fullscreen-stage')}else{document.exitFullscreen?.();document.body.classList.remove('fullscreen-stage')}}
  function wire(){
    ['complexity','density','motion','balance','detail'].forEach(k=>{els[k].addEventListener('input',()=>{syncOutputs();if(coarsePointer){setStatus('Release to apply…')}else{scheduleGenerate(150)}});els[k].addEventListener('change',()=>generate())});
    els.style.addEventListener('change',()=>generate());els.mirror.addEventListener('change',()=>generate());els.quality.addEventListener('change',()=>generate());els.palette.addEventListener('change',rerenderOnly);els.stroke.addEventListener('input',()=>{syncOutputs();rerenderOnly()});els.ratio.addEventListener('change',()=>{settings=read();if(artwork)artwork.settings=Object.assign({},artwork.settings,{ratio:settings.ratio});setRatio();requestAnimationFrame(render)});
    els.seed.addEventListener('change',()=>generate());els.seed.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();generate()}});
    $('randomSeedBtn').onclick=()=>{els.seed.value=JSI.random.makeSeed();generate()};$('generateBtn').onclick=()=>generate({newSeed:true});$('surpriseBtn').onclick=surprise;$('resetBtn').onclick=reset;$('saveBtn').onclick=save;
    $('exportBtn').onclick=()=>$('exportModal').showModal();$('confirmExportBtn').onclick=async()=>{if(!artwork)return;const b=$('confirmExportBtn');b.disabled=true;b.textContent='Preparing…';try{await JSI.exporter.exportArt(artwork,$('exportFormat').value,+$('exportSize').value);$('exportModal').close();setStatus('Exported')}catch(e){console.error(e);setStatus('Export failed')}finally{b.disabled=false;b.textContent='Export file'}};
    $('collectionBtn').onclick=()=>{loadCollection();$('collectionModal').showModal()};$('closeCollectionBtn').onclick=()=>$('collectionModal').close();$('helpBtn').onclick=()=>$('helpModal').showModal();$('closeHelpBtn').onclick=()=>$('helpModal').close();$('fullscreenBtn').onclick=toggleFullscreen;
    $('mobileControlsBtn').onclick=openControls;$('openControlsBtn').onclick=openControls;$('closeControlsBtn').onclick=closeControls;$('backdrop').onclick=closeControls;
    document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('fullscreen-stage')});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('controlPanel').classList.contains('open')){closeControls();return}if(e.target.matches('input,select,textarea'))return;if(e.key.toLowerCase()==='g')generate({newSeed:true});else if(e.key.toLowerCase()==='s')surprise();else if(e.key.toLowerCase()==='e')$('exportModal').showModal();else if(e.key.toLowerCase()==='f')toggleFullscreen()});
    if('ResizeObserver' in window){const ro=new ResizeObserver(()=>requestAnimationFrame(render));ro.observe(els.artboard)}else{window.addEventListener('resize',()=>requestAnimationFrame(render),{passive:true})}
  }
  function init(){populatePalettes();const initial=Object.assign({},JSI.presets.DEFAULTS);applySettingsToControls(initial);els.seed.value=JSI.random.makeSeed();wire();generate()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}());
