(function(){
  'use strict';
  const JSI=window.JSI=window.JSI||{};
  const ratioMap={'4:3':4/3,'1:1':1,'16:9':16/9,'4:5':4/5};
  function palette(art){return JSI.presets.PALETTES[art.settings.palette]||JSI.presets.PALETTES.editorial}
  function color(art,key){if(key===null||key===undefined)return null;const pal=palette(art);return pal.colors[Math.abs(key)%pal.colors.length]}
  function smoothPath(ctx,pts,close){if(!pts.length)return;ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);if(pts.length===2){ctx.lineTo(pts[1][0],pts[1][1])}else{for(let i=1;i<pts.length-1;i++){const mx=(pts[i][0]+pts[i+1][0])/2,my=(pts[i][1]+pts[i+1][1])/2;ctx.quadraticCurveTo(pts[i][0],pts[i][1],mx,my)}ctx.lineTo(pts[pts.length-1][0],pts[pts.length-1][1])}if(close)ctx.closePath()}
  function draw(ctx,w,h,art){const pal=palette(art);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.fillStyle=pal.bg;ctx.fillRect(0,0,w,h);ctx.lineJoin='round';ctx.lineCap='round';const strokeScale=Math.min(w,h)/900*(art.settings.stroke/100);for(const q of art.primitives){ctx.globalAlpha=q.alpha==null?1:q.alpha;ctx.shadowBlur=0;if(q.type==='path'){const pts=q.points.map(([x,y])=>[x*w,y*h]);smoothPath(ctx,pts,q.closed);if(q.fill!==null&&q.fill!==undefined){ctx.fillStyle=color(art,q.fill);ctx.fill()}if(q.stroke!==null&&q.stroke!==undefined){ctx.strokeStyle=color(art,q.stroke);ctx.lineWidth=Math.max(.45,q.width*strokeScale);ctx.stroke()}}else if(q.type==='polygon'){ctx.beginPath();q.points.forEach(([x,y],i)=>i?ctx.lineTo(x*w,y*h):ctx.moveTo(x*w,y*h));ctx.closePath();ctx.fillStyle=color(art,q.fill);ctx.fill();if(q.stroke!==null&&q.stroke!==undefined){ctx.strokeStyle=color(art,q.stroke);ctx.lineWidth=Math.max(.45,q.width*strokeScale);ctx.stroke()}}else if(q.type==='circle'){ctx.beginPath();ctx.arc(q.x*w,q.y*h,q.r*Math.min(w,h),0,Math.PI*2);if(q.fill!==null){ctx.fillStyle=color(art,q.fill);ctx.fill()}if(q.stroke!==null&&q.stroke!==undefined){ctx.strokeStyle=color(art,q.stroke);ctx.lineWidth=Math.max(.45,q.width*strokeScale);ctx.stroke()}}else if(q.type==='arc'){ctx.beginPath();ctx.arc(q.cx*w,q.cy*h,q.r*Math.min(w,h),q.a0,q.a1);ctx.strokeStyle=color(art,q.stroke);ctx.lineWidth=Math.max(.45,q.width*strokeScale);ctx.stroke()}}
    ctx.restore()}
  function fit(canvas,art){const rect=canvas.getBoundingClientRect();const q=JSI.presets.QUALITY[art.settings.quality];let dpr=Math.min(window.devicePixelRatio||1,q.dpr);const coarse=window.matchMedia&&window.matchMedia('(pointer: coarse)').matches;const budget=coarse?1400000:2600000;const projected=Math.max(1,rect.width*rect.height*dpr*dpr);if(projected>budget)dpr=Math.max(1,dpr*Math.sqrt(budget/projected));const w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}return{w,h}}
  function render(canvas,art){if(!art)return;const {w,h}=fit(canvas,art);draw(canvas.getContext('2d',{alpha:false}),w,h,art)}
  function offscreen(art,longEdge){const r=ratioMap[art.settings.ratio]||4/3;let w,h;if(r>=1){w=longEdge;h=Math.round(longEdge/r)}else{h=longEdge;w=Math.round(longEdge*r)}const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d',{alpha:false}),w,h,art);return c}
  function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&apos;','"':'&quot;'}[c]))}
  function svgPath(points,closed){if(!points.length)return'';if(points.length===2)return`M ${points[0][0]} ${points[0][1]} L ${points[1][0]} ${points[1][1]}${closed?' Z':''}`;let d=`M ${points[0][0]} ${points[0][1]} `;for(let i=1;i<points.length-1;i++){const mx=(points[i][0]+points[i+1][0])/2,my=(points[i][1]+points[i+1][1])/2;d+=`Q ${points[i][0]} ${points[i][1]} ${mx} ${my} `}d+=`L ${points[points.length-1][0]} ${points[points.length-1][1]}`;return d+(closed?' Z':'')}
  function toSVG(art,longEdge){const r=ratioMap[art.settings.ratio]||4/3;let w,h;if(r>=1){w=longEdge;h=Math.round(longEdge/r)}else{h=longEdge;w=Math.round(longEdge*r)}const pal=palette(art),strokeScale=Math.min(w,h)/900*(art.settings.stroke/100);const body=[];for(const q of art.primitives){const op=(q.alpha==null?1:q.alpha).toFixed(3);if(q.type==='path'){const pts=q.points.map(([x,y])=>[(x*w).toFixed(2),(y*h).toFixed(2)]);body.push(`<path d="${svgPath(pts,q.closed)}" ${q.fill!==null&&q.fill!==undefined?`fill="${color(art,q.fill)}"`:'fill="none"'} ${q.stroke!==null&&q.stroke!==undefined?`stroke="${color(art,q.stroke)}" stroke-width="${Math.max(.45,q.width*strokeScale).toFixed(2)}" stroke-linecap="round" stroke-linejoin="round"`:''} opacity="${op}"/>`)}else if(q.type==='polygon'){const pts=q.points.map(([x,y])=>`${(x*w).toFixed(2)},${(y*h).toFixed(2)}`).join(' ');body.push(`<polygon points="${pts}" fill="${color(art,q.fill)}" opacity="${op}"/>`)}else if(q.type==='circle'){body.push(`<circle cx="${(q.x*w).toFixed(2)}" cy="${(q.y*h).toFixed(2)}" r="${(q.r*Math.min(w,h)).toFixed(2)}" fill="${color(art,q.fill)}" opacity="${op}"/>`)}else if(q.type==='arc'){const x1=q.cx*w+Math.cos(q.a0)*q.r*Math.min(w,h),y1=q.cy*h+Math.sin(q.a0)*q.r*Math.min(w,h),x2=q.cx*w+Math.cos(q.a1)*q.r*Math.min(w,h),y2=q.cy*h+Math.sin(q.a1)*q.r*Math.min(w,h),large=Math.abs(q.a1-q.a0)>Math.PI?1:0;body.push(`<path d="M ${x1.toFixed(2)} ${y1.toFixed(2)} A ${(q.r*Math.min(w,h)).toFixed(2)} ${(q.r*Math.min(w,h)).toFixed(2)} 0 ${large} 1 ${x2.toFixed(2)} ${y2.toFixed(2)}" fill="none" stroke="${color(art,q.stroke)}" stroke-width="${Math.max(.45,q.width*strokeScale).toFixed(2)}" stroke-linecap="round" opacity="${op}"/>`)}}
    return`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="${esc(art.title)}"><rect width="100%" height="100%" fill="${pal.bg}"/>${body.join('')}</svg>`}
  JSI.renderer={render,offscreen,toSVG,ratioMap};
}());
